src/Controller/Admin/MapAdminController.php
<?php

declare(strict_types=1);

namespace OrienteeringManager\Controller\Admin;

use OrienteeringManager\Builder\UxComponentBuilder\MapUxComponentBuilder;
use OrienteeringManager\Config\Enum\ModeEnum;
use OrienteeringManager\Config\Enum\PageTypeEnum;
use OrienteeringManager\DataProvider\OrienteeringManagerDataProvider;
use OrienteeringManager\Form\Model\OrienteeringManager\Item\MapType;
use OrienteeringManager\Model\OrienteeringManager\Collection\MapApiCollection;
use OrienteeringManager\Model\OrienteeringManager\Filter\ApiFilterInterface;
use OrienteeringManager\Model\OrienteeringManager\Filter\MapApiFilter;
use OrienteeringManager\Model\OrienteeringManager\Item\ApiItemInterface;
use OrienteeringManager\Model\OrienteeringManager\Item\MapApiItem;
use OrienteeringManager\Repository\PageRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/admin/map', name: 'app_admin_map_')]
final class MapAdminController extends AbstractApiItemAdminController
{
    public function __construct(
        private readonly MapUxComponentBuilder $mapUxComponentBuilder,
        TranslatorInterface $translator,
        OrienteeringManagerDataProvider $dataProvider,
        PageRepository $pageRepository,
        ValidatorInterface $validator
    ) {
        parent::__construct($translator, $dataProvider, $pageRepository, $validator);
    }

    protected function getType(): string
    {
        return 'map';
    }

    protected function getPageType(): string
    {
        return PageTypeEnum::MAP_LIST->value;
    }

    protected function getCollectionClass(): string
    {
        return MapApiCollection::class;
    }

    protected function getItemClass(): string
    {
        return MapApiItem::class;
    }

    protected function getFormClass(): string
    {
        return MapType::class;
    }

    protected function getFilterFormClass(): ?string
    {
        return null;
    }

    protected function getFilter(Request $request): ?ApiFilterInterface
    {
        $mapFilter = new MapApiFilter();
        $mapFilter->setItemsPerPage(self::ITEMS_PER_PAGES);
        $mapFilter->setPage($request->query->getInt('page', 1));
        $mapFilter->setMode(ModeEnum::EDIT);

        return $mapFilter;
    }

    /**
     * @param MapApiItem $entity
     */
    protected function getTemplateParameters(ApiItemInterface $entity): array
    {
        $parameters = parent::getTemplateParameters($entity);

        $parameters['map'] = $this->mapUxComponentBuilder->build($entity);

        return $parameters;
    }
}

templates/bundles/TwigBundle/Exception/error.html.twig
{% extends '@OrienteeringManager/base.html.twig' %}

{% block body %}
    <div class="container-fluid container-lg py-4">
        <div class="row">
            <div class="col-12">
                <h1 class="mb-3"><i class="bi bi-bug me-2 text-primary"></i> Erreur {{ status_code }} -  {{ status_text }}</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <p class="lead">
                    Une erreur est survenue empêchant l'accès à la page demandée. Veuillez transmettre les informations ci-dessous à Quentin.
                </p>

                <a class="btn btn-lg btn-primary" href="{{ path('app_homepage') }}">
                    <i class="bi bi-house me-2"></i>
                    Retour à l'accueil
                </a>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-12 overflow-x-auto">
                <div class="h3 text-danger">{{ exception.message }}</div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><i class="bi bi-file-earmark-code me-4 text-danger"></i> {{ exception.file }}</li>
                    <li class="list-group-item"><i class="bi bi-terminal me-4 text-danger"></i> {{ exception.line }}</li>
                </ul>

                {% for trace in exception.trace %}
                    <div class="my-1">
                        {{ '%s at line %s : %s%s%s()'|format(trace.file, trace.line, trace.class, trace.type, trace.function) }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/bundles/TwigBundle/Exception/error404.html.twig
{% extends '@OrienteeringManager/base.html.twig' %}

{% block body %}
    <div class="container-fluid container-lg py-4">
        <div class="row">
            <div class="col-12">
                <h1 class="mb-3"><i class="text-primary bi bi-file-x me-2 text-primary"></i> Page introuvable</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <p class="lead">
                    La page demandé n'existe pas ou celle-ci a été supprimée.
                </p>

                <a class="btn btn-lg btn-primary" href="{{ path('app_homepage') }}">
                    <i class="bi bi-house me-2"></i>
                    Retour à l'accueil
                </a>
            </div>
        </div>
    </div>
{% endblock %}